/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    NutTimeDetail: typeof import('@nutui/nutui-taro')['TimeDetail']
    NutTimePannel: typeof import('@nutui/nutui-taro')['TimePannel']
    NutTimeSelect: typeof import('@nutui/nutui-taro')['TimeSelect']
    Waterfall: typeof import('./src/components/waterfall/index.vue')['default']
  }
}
